<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "logentries"
 *
 * Auto generated by Extension Builder 2013-12-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'LogEntries logger',
	'description' => 'Provides a logger that sends data to LogEntries.com',
	'category' => 'services',
	'author' => 'Julien Henchoz',
	'author_email' => 'typo3@cobweb.ch',
	'author_company' => 'Cobweb Development SARL',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
