<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "logentries"
 *
 * Auto generated by Extension Builder 2013-12-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
        'title' => 'LogEntries logger',
        'description' => 'Provides a logger that sends data to LogEntries.com',
        'category' => 'services',
        'author' => 'Julien Henchoz',
        'author_email' => 'typo3@ideative.ch',
        'author_company' => 'Idéative',
        'shy' => '',
        'priority' => '',
        'module' => '',
        'state' => 'stable',
        'internal' => '',
        'uploadfolder' => '0',
        'createDirs' => '',
        'modify_tables' => '',
        'clearCacheOnLoad' => 0,
        'lockType' => '',
        'version' => '1.2.0',
        'constraints' => [
                'depends' => [
                        'typo3' => '9.5.0-9.5.99',
                ],
                'conflicts' => [
                ],
                'suggests' => [
                ],
        ],
];
